// @vitest-environment node
import { execFileSync, spawn, type ChildProcess } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterAll, describe, expect, it } from 'vitest';

/**
 * The slice-6 LIFECYCLE gate: a project generated by the REAL built CLI must typecheck, boot a dev
 * server that responds, build client and SSR, and boot a production server that responds.
 *
 * Generation goes through the shipped binary with the frozen non-interactive flags - deliberately
 * NOT through `planFiles`, which is fast template/golden coverage and is not lifecycle evidence.
 *
 * Dependencies resolve through the BUILT workspace packages via their real export maps (`link:`),
 * never from a registry - `@taujs/solid` is private and unpublished, so a registry install could
 * not work and must not be depended on.
 *
 * Every spawned process and bound port is released on success AND on failure.
 */
const REPO_ROOT = fileURLToPath(new URL('../../../../', import.meta.url));
const CLI = fileURLToPath(new URL('../../dist/index.js', import.meta.url));

const WORKSPACE_LINKS: Record<string, string> = {
  '@taujs/server': path.join(REPO_ROOT, 'packages/server'),
  '@taujs/solid': path.join(REPO_ROOT, 'packages/solid'),
  '@taujs/react': path.join(REPO_ROOT, 'packages/react'),
  '@taujs/vue': path.join(REPO_ROOT, 'packages/vue'),
  '@taujs/mcp': path.join(REPO_ROOT, 'packages/mcp'),
};

/** Every child this suite starts, so teardown can be exhaustive even if an assertion throws. */
const spawned = new Set<ChildProcess>();
const scratchDirs = new Set<string>();

const killTree = (child: ChildProcess) => {
  if (child.exitCode !== null || child.signalCode !== null) return;
  try {
    // Negative pid targets the whole process group, so tsx's child server dies with the wrapper.
    if (child.pid) process.kill(-child.pid, 'SIGKILL');
  } catch {
    try {
      child.kill('SIGKILL');
    } catch {}
  }
};

afterAll(() => {
  for (const child of spawned) killTree(child);
  spawned.clear();
  for (const dir of scratchDirs) rmSync(dir, { recursive: true, force: true });
  scratchDirs.clear();
});

/** The port the GENERATED config declares - read, never rewritten. */
const generatedPort = (dir: string): number => {
  const match = /port:\s*(\d+)/.exec(readFileSync(path.join(dir, 'taujs.config.ts'), 'utf8'));
  if (!match) throw new Error('could not read the generated server port from taujs.config.ts');

  return Number(match[1]);
};

/** Bind-probe a free port, then release it - never assume a fixed port is available. */
const freePort = async (): Promise<number> =>
  new Promise((resolve, reject) => {
    const probe = createServer();
    probe.once('error', reject);
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address();
      const port = typeof address === 'object' && address ? address.port : 0;
      probe.close(() => resolve(port));
    });
  });

const isPortFree = async (port: number): Promise<boolean> =>
  new Promise((resolve) => {
    const probe = createServer();
    probe.once('error', () => resolve(false));
    probe.listen(port, '127.0.0.1', () => probe.close(() => resolve(true)));
  });

const waitForResponse = async (url: string, child: ChildProcess, timeoutMs = 90_000): Promise<Response> => {
  const deadline = Date.now() + timeoutMs;
  let lastError: unknown;

  while (Date.now() < deadline) {
    if (child.exitCode !== null) throw new Error(`server exited early with code ${child.exitCode}`);
    try {
      return await fetch(url);
    } catch (e) {
      lastError = e;
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  throw new Error(`server did not respond at ${url} within ${timeoutMs}ms: ${String(lastError)}`);
};

const startServer = (cwd: string, script: string, env: Record<string, string>) => {
  const child = spawn('npm', ['run', script], {
    cwd,
    env: { ...process.env, ...env },
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: true, // its own process group, so killTree reaches tsx's grandchildren
  });
  spawned.add(child);

  let output = '';
  child.stdout?.on('data', (c: Buffer) => (output += String(c)));
  child.stderr?.on('data', (c: Buffer) => (output += String(c)));

  return { child, output: () => output };
};

/**
 * Run the identical eight steps per framework. Solid is the slice-6 subject; REACT is the CONTROL,
 * present to prove the two scaffolder-baseline corrections (the `types.d.ts` module augmentation
 * and the `esbuild` devDependency) are SHARED REPAIRS rather than Solid-specific accommodations.
 */
describe.each(['solid', 'react'] as const)('slice 6 - generated %s project lifecycle (through the real CLI)', (framework) => {
  // One generated project drives the whole sequence; the steps are ordered and share state.
  let projectDir = '';
  let devPort = 0;
  let prodPort = 0;

  it('1. the built CLI generates a project with NO TTY and exits 0', () => {
    expect(existsSync(CLI), `CLI dist missing at ${CLI} - run \`pnpm build\` first`).toBe(true);

    const workDir = mkdtempSync(path.join(tmpdir(), 'taujs-lifecycle-'));
    scratchDirs.add(workDir);

    // The frozen non-interactive interface. `stdio: 'ignore'` for stdin proves no TTY is needed.
    execFileSync(process.execPath, [CLI, 'demo-app', '--framework', framework, '--package-manager', 'npm', '--no-install'], {
      cwd: workDir,
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    projectDir = path.join(workDir, 'demo-app');
    expect(existsSync(projectDir)).toBe(true);
  });

  it('2. the generated files match the asserted plan', () => {
    const read = (rel: string) => readFileSync(path.join(projectDir, rel), 'utf8');

    // Shared baseline, both frameworks: the augmentation must IMPORT before declaring, and
    // esbuild must be declared because build:server shells out to its binary.
    const augmentation = read('src/server/types.d.ts');
    expect(augmentation.startsWith("import '@taujs/server/config';")).toBe(true);
    expect(JSON.parse(read('package.json')).devDependencies.esbuild).toBeTruthy();

    if (framework === 'solid') {
      expect(read('taujs.config.ts')).toContain("renderer: solidRenderer({ project: './tsconfig.solid.json' }),");
      expect(read('taujs.config.ts')).not.toContain('vite-plugin-solid');
      expect(read('src/client/entry-server.tsx')).toContain("import { createRenderer } from '@taujs/solid';");
      expect(read('src/client/entry-client.tsx')).toContain("import { hydrateApp } from '@taujs/solid';");
      expect(JSON.parse(read('tsconfig.solid.json')).include).toEqual(['src/client/**/*.tsx']);
    } else {
      expect(read('taujs.config.ts')).toContain('reactRenderer({');
      expect(read('src/client/entry-server.tsx')).toContain("import { createRenderer } from '@taujs/react';");
    }
  });

  it('3. dependencies resolve through the BUILT workspace packages, not a registry', { timeout: 600_000 }, () => {
    const pkgPath = path.join(projectDir, 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };

    // `@taujs/solid` is private and unpublished - a registry install cannot work and must not be
    // relied on. Point every τjs dependency at the built workspace package so resolution goes
    // through its REAL export map.
    for (const [name, location] of Object.entries(WORKSPACE_LINKS)) {
      expect(existsSync(path.join(location, 'dist')), `${name} is not built - run \`pnpm -r build\` first`).toBe(true);
      if (pkg.dependencies[name]) pkg.dependencies[name] = `link:${location}`;
      if (pkg.devDependencies[name]) pkg.devDependencies[name] = `link:${location}`;
    }
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

    // `--ignore-workspace` keeps this install out of the repo's own workspace graph.
    execFileSync('pnpm', ['install', '--ignore-workspace', '--no-frozen-lockfile'], { cwd: projectDir, stdio: 'pipe' });

    // Resolution really goes through the export map, not a guessed path. `import.meta.resolve`,
    // not `require.resolve`: these packages are ESM-ONLY (their exports declare `import` and no
    // `require`), so a CJS resolve cannot see the subpath at all.
    const resolved = execFileSync(
      process.execPath,
      ['--input-type=module', '-e', `console.log(import.meta.resolve('@taujs/${framework}/renderer'))`],
      { cwd: projectDir, encoding: 'utf8' },
    );
    expect(resolved).toContain(`${framework}/dist/renderer.js`);
  });

  it('4. the generated project typechecks', { timeout: 300_000 }, () => {
    execFileSync('npm', ['run', 'lint'], { cwd: projectDir, stdio: 'pipe' });
  });

  it('5. the development server boots and responds', { timeout: 300_000 }, async () => {
    // The GENERATED config's own ports are used as-is. The project is never edited after creation
    // (beyond the dependency links in step 3), so nothing here can mask a generator defect by
    // patching the output into working shape.
    devPort = generatedPort(projectDir);
    expect(await isPortFree(devPort), `generated dev port ${devPort} is already in use - cannot run the lifecycle gate`).toBe(true);

    const { child, output } = startServer(projectDir, 'dev', {});
    try {
      const response = await waitForResponse(`http://127.0.0.1:${devPort}/`, child);

      expect(response.status, `dev server responded ${response.status}\n${output()}`).toBe(200);
      const html = await response.text();
      expect(html).toContain('window.__INITIAL_DATA__');
      if (framework === 'solid') expect(html).toContain('τjs + Solid');
    } finally {
      killTree(child);
    }
  });

  it('6. the client and SSR builds pass', { timeout: 600_000 }, () => {
    execFileSync('npm', ['run', 'build:client'], { cwd: projectDir, stdio: 'pipe' });
    execFileSync('npm', ['run', 'build:entry-server'], { cwd: projectDir, stdio: 'pipe' });
    execFileSync('npm', ['run', 'build:server'], { cwd: projectDir, stdio: 'pipe' });

    expect(existsSync(path.join(projectDir, 'dist/client'))).toBe(true);
    expect(existsSync(path.join(projectDir, 'dist/server/index.js'))).toBe(true);
  });

  it('7. the production server boots and responds', { timeout: 300_000 }, async () => {
    // Same generated port; step 5's server is already down (its `finally` killed it).
    prodPort = generatedPort(projectDir);
    expect(await isPortFree(prodPort), `generated port ${prodPort} is still bound before the production boot`).toBe(true);

    const { child, output } = startServer(projectDir, 'start', {});
    try {
      const response = await waitForResponse(`http://127.0.0.1:${prodPort}/`, child);

      expect(response.status, `production server responded ${response.status}\n${output()}`).toBe(200);
      const html = await response.text();
      expect(html).toContain('window.__INITIAL_DATA__');
    } finally {
      killTree(child);
    }
  });

  it('8. every spawned process is dead and every port released', async () => {
    for (const child of spawned) killTree(child);
    await new Promise((r) => setTimeout(r, 500));

    for (const child of spawned) {
      expect(child.exitCode !== null || child.signalCode !== null, 'a spawned server is still running').toBe(true);
    }
    for (const port of [devPort, prodPort].filter(Boolean)) {
      expect(await isPortFree(port), `port ${port} is still bound`).toBe(true);
    }
  });
});
