// @vitest-environment node
import { execFileSync, spawn, type ChildProcess } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterAll, describe, expect, it } from 'vitest';

/**
 * The slice-6 LIFECYCLE gate: a project generated by the REAL built CLI must typecheck, boot a dev
 * server that responds, build, and boot a production server that responds.
 *
 * Design of this harness, deliberately:
 *
 * - ONE test per framework, run as a fail-fast TRANSACTION with named stages. Eight interdependent
 *   tests sharing mutable state reported cascade failures - a broken stage 3 "failed" stages 4-7 -
 *   which buried the real cause. A transaction reports the FIRST failing stage and stops.
 * - The user-facing `npm run build` is invoked, NOT its three component scripts. The composite is
 *   what is claimed to work, and it is a distinct script that can drift from its parts.
 * - Dependencies are installed from PACKED TARBALLS (`npm pack`), exactly as a user receives them,
 *   so the export map, the `files` allow-list and the packed declarations are all exercised.
 *   Linking the source directory would silently tolerate a broken `files` field.
 * - The generated project is NOT edited after creation beyond its dependency versions: its own
 *   ports are read and bind-probed, never rewritten.
 * - Teardown awaits actual process exit and polls until the port is released - no fixed sleeps.
 *
 * React runs the identical stages as a CONTROL, proving the scaffolder-baseline corrections are
 * shared repairs rather than Solid-specific accommodations.
 */
const REPO_ROOT = fileURLToPath(new URL('../../../../', import.meta.url));
const CLI = fileURLToPath(new URL('../../dist/index.js', import.meta.url));

const PACKABLE: Record<string, string> = {
  '@taujs/server': path.join(REPO_ROOT, 'packages/server'),
  '@taujs/solid': path.join(REPO_ROOT, 'packages/solid'),
  '@taujs/react': path.join(REPO_ROOT, 'packages/react'),
  '@taujs/vue': path.join(REPO_ROOT, 'packages/vue'),
  '@taujs/mcp': path.join(REPO_ROOT, 'packages/mcp'),
};

const spawned = new Set<ChildProcess>();
const scratchDirs = new Set<string>();

const isPortFree = async (port: number): Promise<boolean> =>
  new Promise((resolve) => {
    const probe = createServer();
    probe.once('error', () => resolve(false));
    probe.listen(port, '127.0.0.1', () => probe.close(() => resolve(true)));
  });

const killTree = (child: ChildProcess) => {
  if (child.exitCode !== null || child.signalCode !== null) return;
  try {
    // Negative pid targets the whole process group, so tsx's child server dies with the wrapper.
    if (child.pid) process.kill(-child.pid, 'SIGKILL');
  } catch {
    try {
      child.kill('SIGKILL');
    } catch {}
  }
};

/** Await actual exit, then poll until the port is genuinely released. Bounded; no fixed sleeps. */
const stopServer = async (child: ChildProcess, port: number, timeoutMs = 15_000) => {
  const exited = new Promise<void>((resolve) => {
    if (child.exitCode !== null || child.signalCode !== null) return resolve();
    child.once('exit', () => resolve());
  });

  killTree(child);
  await Promise.race([exited, new Promise((r) => setTimeout(r, timeoutMs))]);

  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await isPortFree(port)) return;
    await new Promise((r) => setTimeout(r, 50));
  }

  throw new Error(`port ${port} was still bound ${timeoutMs}ms after the server was killed`);
};

afterAll(() => {
  for (const child of spawned) killTree(child);
  spawned.clear();
  for (const dir of scratchDirs) rmSync(dir, { recursive: true, force: true });
  scratchDirs.clear();
});

/** The port the GENERATED config declares - read, never rewritten. */
const generatedPort = (dir: string): number => {
  const match = /port:\s*(\d+)/.exec(readFileSync(path.join(dir, 'taujs.config.ts'), 'utf8'));
  if (!match) throw new Error('could not read the generated server port from taujs.config.ts');

  return Number(match[1]);
};

const waitForResponse = async (url: string, child: ChildProcess, output: () => string, timeoutMs = 90_000): Promise<Response> => {
  const deadline = Date.now() + timeoutMs;
  let lastError: unknown;

  while (Date.now() < deadline) {
    if (child.exitCode !== null) throw new Error(`server exited early with code ${child.exitCode}\n${output()}`);
    try {
      return await fetch(url);
    } catch (e) {
      lastError = e;
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  throw new Error(`server did not respond at ${url} within ${timeoutMs}ms: ${String(lastError)}\n${output()}`);
};

const startServer = (cwd: string, script: string) => {
  const child = spawn('npm', ['run', script], { cwd, stdio: ['ignore', 'pipe', 'pipe'], detached: true });
  spawned.add(child);

  let output = '';
  child.stdout?.on('data', (c: Buffer) => (output += String(c)));
  child.stderr?.on('data', (c: Buffer) => (output += String(c)));

  return { child, output: () => output };
};

/** Pack every workspace package once; both frameworks install identical, user-shaped tarballs. */
let packedCache: Record<string, string> | undefined;
const packAll = (): Record<string, string> => {
  if (packedCache) return packedCache;

  // Into a scratch dir, never the repo: tarballs are build artefacts and must not appear in
  // `git status`.
  const into = mkdtempSync(path.join(tmpdir(), 'taujs-packed-'));
  scratchDirs.add(into);
  for (const [name, dir] of Object.entries(PACKABLE)) {
    if (!existsSync(path.join(dir, 'dist'))) throw new Error(`${name} is not built - run \`pnpm -r build\` first`);
    execFileSync('npm', ['pack', '--pack-destination', into], { cwd: dir, stdio: 'pipe' });
  }

  const packed: Record<string, string> = {};
  for (const file of readdirSync(into).filter((f) => f.endsWith('.tgz'))) {
    // `taujs-solid-0.1.0.tgz` -> `@taujs/solid`
    const scoped = /^taujs-(.+?)-\d+\.\d+\.\d+.*\.tgz$/.exec(file);
    if (scoped) packed[`@taujs/${scoped[1]}`] = path.join(into, file);
  }
  packedCache = packed;

  return packed;
};

type Stage = { name: string; run: () => void | Promise<void> };

/** Run named stages in order, stopping at the FIRST failure and naming the stage that failed. */
const runTransaction = async (stages: Stage[]): Promise<string[]> => {
  const completed: string[] = [];

  for (const stage of stages) {
    try {
      await stage.run();
      completed.push(stage.name);
    } catch (e) {
      const trail = completed.length > 0 ? completed.join(' -> ') : 'none';
      throw new Error(`lifecycle FAILED at stage "${stage.name}" (completed: ${trail})\n\n${String((e as Error).message)}`);
    }
  }

  return completed;
};

describe.each(['solid', 'react'] as const)('slice 6 - generated %s project lifecycle (real CLI, packed tarballs)', (framework) => {
  it('generates, installs, typechecks, boots dev, builds, and boots production', { timeout: 900_000 }, async () => {
    if (!existsSync(CLI)) throw new Error(`CLI dist missing at ${CLI} - run \`pnpm build\` first`);

    const workDir = mkdtempSync(path.join(tmpdir(), `taujs-lifecycle-${framework}-`));
    scratchDirs.add(workDir);
    const projectDir = path.join(workDir, 'demo-app');
    let port = 0;

    const completed = await runTransaction([
      {
        name: '1 built CLI generates with no TTY',
        run: () => {
          // stdin is 'ignore' - there is no TTY and nothing to read. This is the CI/agent contract.
          execFileSync(process.execPath, [CLI, 'demo-app', '--framework', framework, '--package-manager', 'npm', '--no-install'], {
            cwd: workDir,
            stdio: ['ignore', 'pipe', 'pipe'],
          });
          expect(existsSync(projectDir)).toBe(true);
        },
      },
      {
        name: '2 generated files match the asserted plan',
        run: () => {
          const read = (rel: string) => readFileSync(path.join(projectDir, rel), 'utf8');

          // Shared scaffolder baseline, asserted for BOTH frameworks.
          expect(read('src/server/types.d.ts').startsWith("import '@taujs/server/config';")).toBe(true);
          const pkg = JSON.parse(read('package.json')) as { devDependencies: Record<string, string>; scripts: Record<string, string> };
          expect(pkg.devDependencies.esbuild).toBeTruthy();
          expect(pkg.scripts.build).toContain('NODE_ENV=production');

          if (framework === 'solid') {
            expect(read('taujs.config.ts')).toContain("renderer: solidRenderer({ project: './tsconfig.solid.json' }),");
            expect(read('taujs.config.ts')).not.toContain('vite-plugin-solid');
            expect(read('src/client/entry-server.tsx')).toContain("import { createRenderer } from '@taujs/solid';");
            expect(read('src/client/entry-client.tsx')).toContain("import { hydrateApp } from '@taujs/solid';");
            expect(JSON.parse(read('tsconfig.solid.json')).include).toEqual(['src/client/**/*.tsx']);
          } else {
            expect(read('taujs.config.ts')).toContain('reactRenderer({');
            expect(read('src/client/entry-server.tsx')).toContain("import { createRenderer } from '@taujs/react';");
          }
        },
      },
      {
        name: '3 install PACKED tarballs (exactly what a user receives)',
        run: () => {
          const packed = packAll();

          // Installing the TARBALL, not the source directory: this exercises the export map, the
          // `files` allow-list and the packed declarations as published.
          const pkgPath = path.join(projectDir, 'package.json');
          const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
            dependencies: Record<string, string>;
            devDependencies: Record<string, string>;
          };
          for (const [name, tarball] of Object.entries(packed)) {
            if (pkg.dependencies?.[name]) pkg.dependencies[name] = `file:${tarball}`;
            if (pkg.devDependencies?.[name]) pkg.devDependencies[name] = `file:${tarball}`;
          }
          writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

          execFileSync('npm', ['install', '--no-audit', '--no-fund'], { cwd: projectDir, stdio: 'pipe' });

          // Resolution goes through the export map. `import.meta.resolve`, not `require.resolve`:
          // these packages are ESM-only, so a CJS resolve cannot see their subpaths at all.
          const resolved = execFileSync(process.execPath, ['--input-type=module', '-e', `console.log(import.meta.resolve('@taujs/${framework}/renderer'))`], {
            cwd: projectDir,
            encoding: 'utf8',
          });
          expect(resolved).toContain(`${framework}/dist/renderer.js`);
        },
      },
      {
        name: '4 typecheck',
        run: () => {
          execFileSync('npm', ['run', 'lint'], { cwd: projectDir, stdio: 'pipe' });
        },
      },
      {
        name: '5 dev server boots and responds',
        run: async () => {
          port = generatedPort(projectDir);
          expect(await isPortFree(port), `generated port ${port} is already in use`).toBe(true);

          const { child, output } = startServer(projectDir, 'dev');
          try {
            const response = await waitForResponse(`http://127.0.0.1:${port}/`, child, output);

            expect(response.status, `dev responded ${response.status}\n${output()}`).toBe(200);
            const html = await response.text();
            expect(html).toContain('window.__INITIAL_DATA__');
            if (framework === 'solid') expect(html).toContain('τjs + Solid');
          } finally {
            await stopServer(child, port);
          }
        },
      },
      {
        name: '6 npm run build (the user-facing composite)',
        run: () => {
          // The COMPOSITE script, not its three parts run separately - that is the command being
          // claimed to work, and it is a distinct script that can drift from its components.
          execFileSync('npm', ['run', 'build'], { cwd: projectDir, stdio: 'pipe' });

          expect(existsSync(path.join(projectDir, 'dist/client'))).toBe(true);
          expect(existsSync(path.join(projectDir, 'dist/server/index.js'))).toBe(true);
        },
      },
      {
        name: '7 production server boots and responds',
        run: async () => {
          expect(await isPortFree(port), `port ${port} still bound before the production boot`).toBe(true);

          const { child, output } = startServer(projectDir, 'start');
          try {
            const response = await waitForResponse(`http://127.0.0.1:${port}/`, child, output);

            expect(response.status, `production responded ${response.status}\n${output()}`).toBe(200);
            expect(await response.text()).toContain('window.__INITIAL_DATA__');
          } finally {
            await stopServer(child, port);
          }
        },
      },
      {
        name: '8 every process dead and port released',
        run: async () => {
          for (const child of spawned) {
            expect(child.exitCode !== null || child.signalCode !== null, 'a spawned server is still running').toBe(true);
          }
          expect(await isPortFree(port), `port ${port} is still bound`).toBe(true);
        },
      },
    ]);

    expect(completed).toHaveLength(8);
  });
});
