// @vitest-environment node
import { execFileSync, spawn, type ChildProcess } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { createServer, type AddressInfo } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { Client } from '@modelcontextprotocol/client';
import { StdioClientTransport } from '@modelcontextprotocol/client/stdio';
import { afterAll, describe, expect, it } from 'vitest';

/**
 * The slice-6 LIFECYCLE gate: a project generated by the REAL built CLI must typecheck, boot a dev
 * server that responds, build, and boot a production server that responds.
 *
 * Design of this harness, deliberately:
 *
 * - ONE test per framework, run as a fail-fast TRANSACTION with named stages. Eight interdependent
 *   tests sharing mutable state reported cascade failures - a broken stage 3 "failed" stages 4-7 -
 *   which buried the real cause. A transaction reports the FIRST failing stage and stops.
 * - The user-facing `npm run build` is invoked, NOT its three component scripts. The composite is
 *   what is claimed to work, and it is a distinct script that can drift from its parts.
 * - Dependencies are installed from PACKED TARBALLS (`npm pack`), exactly as a user receives them,
 *   so the export map, the `files` allow-list and the packed declarations are all exercised.
 *   Linking the source directory would silently tolerate a broken `files` field.
 * - The generated project is NOT edited after creation beyond its dependency versions: its own
 *   ports are read and bind-probed, never rewritten.
 * - Teardown awaits actual process exit and polls until the port is released - no fixed sleeps.
 *
 * React runs the identical stages as a CONTROL, proving the scaffolder-baseline corrections are
 * shared repairs rather than Solid-specific accommodations. Vue joined on 2026-07-30 (derived
 * type-chain work), so the generated chain is compiler-proven for all three frameworks.
 */
const REPO_ROOT = fileURLToPath(new URL('../../../../', import.meta.url));
const CLI = fileURLToPath(new URL('../../dist/index.js', import.meta.url));

const PACKABLE: Record<string, string> = {
  '@taujs/server': path.join(REPO_ROOT, 'packages/server'),
  '@taujs/solid': path.join(REPO_ROOT, 'packages/solid'),
  '@taujs/react': path.join(REPO_ROOT, 'packages/react'),
  '@taujs/vue': path.join(REPO_ROOT, 'packages/vue'),
  '@taujs/mcp': path.join(REPO_ROOT, 'packages/mcp'),
};

const spawned = new Set<ChildProcess>();
const scratchDirs = new Set<string>();

/** Whether HOST specifically can bind PORT right now - the exact address the child is told to use. */
const canBind = async (host: string, port: number): Promise<boolean> =>
  new Promise((resolve) => {
    const probe = createServer();
    probe.once('error', () => resolve(false));
    probe.listen(port, host, () => probe.close(() => resolve(true)));
  });

/** Two distinct ephemeral 127.0.0.1 ports, bound SIMULTANEOUSLY so the OS cannot hand back the same one twice. */
const allocatePortPair = async (): Promise<[number, number]> => {
  const bind = () =>
    new Promise<ReturnType<typeof createServer>>((resolve, reject) => {
      const server = createServer();
      server.once('error', reject);
      server.listen(0, '127.0.0.1', () => resolve(server));
    });

  const [a, b] = await Promise.all([bind(), bind()]);
  const [portA, portB] = [(a.address() as AddressInfo).port, (b.address() as AddressInfo).port];

  await Promise.all([a, b].map((s) => new Promise<void>((resolve) => s.close(() => resolve()))));

  return [portA, portB];
};

const killTree = (child: ChildProcess) => {
  if (child.exitCode !== null || child.signalCode !== null) return;
  try {
    // Negative pid targets the whole process group, so tsx's child server dies with the wrapper.
    if (child.pid) process.kill(-child.pid, 'SIGKILL');
  } catch {
    try {
      child.kill('SIGKILL');
    } catch {}
  }
};

/** Await actual exit, then poll until every given port is genuinely released. Bounded; no fixed sleeps. */
const stopServer = async (child: ChildProcess, ports: readonly number[], timeoutMs = 15_000) => {
  const exited = new Promise<void>((resolve) => {
    if (child.exitCode !== null || child.signalCode !== null) return resolve();
    child.once('exit', () => resolve());
  });

  killTree(child);
  await Promise.race([exited, new Promise((r) => setTimeout(r, timeoutMs))]);

  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const free = await Promise.all(ports.map((port) => canBind('127.0.0.1', port)));
    if (free.every(Boolean)) return;
    await new Promise((r) => setTimeout(r, 50));
  }

  throw new Error(`port(s) ${ports.join(', ')} still bound ${timeoutMs}ms after the server was killed`);
};

afterAll(() => {
  for (const child of spawned) killTree(child);
  spawned.clear();
  for (const dir of scratchDirs) rmSync(dir, { recursive: true, force: true });
  scratchDirs.clear();
});

/** The port the GENERATED config declares - read, never rewritten, never used for binding. */
const generatedPort = (dir: string): number => {
  const match = /port:\s*(\d+)/.exec(readFileSync(path.join(dir, 'taujs.config.ts'), 'utf8'));
  if (!match) throw new Error('could not read the generated server port from taujs.config.ts');

  return Number(match[1]);
};

/** The HMR port the GENERATED config declares - read, never rewritten, never used for binding. */
const generatedHmrPort = (dir: string): number => {
  const match = /hmrPort:\s*(\d+)/.exec(readFileSync(path.join(dir, 'taujs.config.ts'), 'utf8'));
  if (!match) throw new Error('could not read the generated HMR port from taujs.config.ts');

  return Number(match[1]);
};

const waitForResponse = async (url: string, child: ChildProcess, output: () => string, timeoutMs = 90_000): Promise<Response> => {
  const deadline = Date.now() + timeoutMs;
  let lastError: unknown;

  while (Date.now() < deadline) {
    if (child.exitCode !== null) throw new Error(`server exited early with code ${child.exitCode}\n${output()}`);
    try {
      return await fetch(url);
    } catch (e) {
      lastError = e;
      await new Promise((r) => setTimeout(r, 250));
    }
  }

  throw new Error(`server did not respond at ${url} within ${timeoutMs}ms: ${String(lastError)}\n${output()}`);
};

/**
 * Spawns with an EXPLICIT env: the three keys are always overwritten so ambient PORT/HOST/HMR_PORT
 * in the caller's shell can never leak in. These are supported inputs, not additions the test makes
 * up (packages/server/src/network/CLI.ts:43-47, utils/DevServer.ts:99-100).
 */
const startServer = (cwd: string, script: string, net: { appPort: number; hmrPort: number }) => {
  const env = { ...process.env, HOST: '127.0.0.1', PORT: String(net.appPort), HMR_PORT: String(net.hmrPort) };
  const child = spawn('npm', ['run', script], { cwd, stdio: ['ignore', 'pipe', 'pipe'], detached: true, env });
  spawned.add(child);

  let output = '';
  child.stdout?.on('data', (c: Buffer) => (output += String(c)));
  child.stderr?.on('data', (c: Buffer) => (output += String(c)));

  return { child, output: () => output };
};

/** Pack every workspace package once; all three frameworks install identical, user-shaped tarballs. */
let packedCache: Record<string, string> | undefined;
const packAll = (): Record<string, string> => {
  if (packedCache) return packedCache;

  // Into a scratch dir, never the repo: tarballs are build artefacts and must not appear in
  // `git status`.
  const into = mkdtempSync(path.join(tmpdir(), 'taujs-packed-'));
  scratchDirs.add(into);
  for (const [name, dir] of Object.entries(PACKABLE)) {
    if (!existsSync(path.join(dir, 'dist'))) throw new Error(`${name} is not built - run \`pnpm -r build\` first`);
    execFileSync('npm', ['pack', '--pack-destination', into], { cwd: dir, stdio: 'pipe' });
  }

  const packed: Record<string, string> = {};
  for (const file of readdirSync(into).filter((f) => f.endsWith('.tgz'))) {
    // `taujs-solid-0.1.0.tgz` -> `@taujs/solid`
    const scoped = /^taujs-(.+?)-\d+\.\d+\.\d+.*\.tgz$/.exec(file);
    if (scoped) packed[`@taujs/${scoped[1]}`] = path.join(into, file);
  }
  packedCache = packed;

  return packed;
};

type Stage = { name: string; run: () => void | Promise<void> };

/** Run named stages in order, stopping at the FIRST failure and naming the stage that failed. */
const runTransaction = async (stages: Stage[]): Promise<string[]> => {
  const completed: string[] = [];

  for (const stage of stages) {
    try {
      await stage.run();
      completed.push(stage.name);
    } catch (e) {
      const trail = completed.length > 0 ? completed.join(' -> ') : 'none';
      throw new Error(`lifecycle FAILED at stage "${stage.name}" (completed: ${trail})\n\n${String((e as Error).message)}`);
    }
  }

  return completed;
};

describe.each(['solid', 'react', 'vue'] as const)('slice 6 - generated %s project lifecycle (real CLI, packed tarballs)', (framework) => {
  it('generates, installs, typechecks, boots dev, builds, and boots production', { timeout: 900_000 }, async () => {
    if (!existsSync(CLI)) throw new Error(`CLI dist missing at ${CLI} - run \`pnpm build\` first`);

    const workDir = mkdtempSync(path.join(tmpdir(), `taujs-lifecycle-${framework}-`));
    scratchDirs.add(workDir);
    const projectDir = path.join(workDir, 'demo-app');
    let appPort = 0;
    let hmrPort = 0;

    const completed = await runTransaction([
      {
        name: '1 built CLI generates with no TTY',
        run: () => {
          // stdin is 'ignore' - there is no TTY and nothing to read. This is the CI/agent contract.
          execFileSync(process.execPath, [CLI, 'demo-app', '--framework', framework, '--package-manager', 'npm', '--no-install'], {
            cwd: workDir,
            stdio: ['ignore', 'pipe', 'pipe'],
          });
          expect(existsSync(projectDir)).toBe(true);
        },
      },
      {
        name: '2 generated files match the asserted plan',
        run: () => {
          const read = (rel: string) => readFileSync(path.join(projectDir, rel), 'utf8');

          // Shared scaffolder baseline, asserted for ALL THREE frameworks.
          expect(read('src/server/types.d.ts').startsWith("import '@taujs/server/config';")).toBe(true);
          const pkg = JSON.parse(read('package.json')) as { devDependencies: Record<string, string>; scripts: Record<string, string> };
          expect(pkg.devDependencies.esbuild).toBeTruthy();
          expect(pkg.scripts.build).toContain('NODE_ENV=production');

          // The GENERATED config's declared public defaults - never the ports this run actually
          // binds, which are allocated fresh in stage 5.
          expect(generatedPort(projectDir)).toBe(5173);
          expect(generatedHmrPort(projectDir)).toBe(5174);

          if (framework === 'solid') {
            expect(read('taujs.config.ts')).toContain("renderer: solidRenderer({ project: './tsconfig.solid.json' }),");
            expect(read('taujs.config.ts')).not.toContain('vite-plugin-solid');
            expect(read('src/client/entry-server.tsx')).toContain("import { createRenderer } from '@taujs/solid';");
            expect(read('src/client/entry-client.tsx')).toContain("import { hydrateApp } from '@taujs/solid';");
            expect(JSON.parse(read('tsconfig.solid.json')).include).toEqual(['src/client/**/*.tsx']);
          } else if (framework === 'react') {
            expect(read('taujs.config.ts')).toContain('reactRenderer({');
            expect(read('src/client/entry-server.tsx')).toContain("import { createRenderer } from '@taujs/react';");
          } else {
            expect(read('taujs.config.ts')).toContain('renderer: vueRenderer(),');
            expect(read('src/client/entry-server.ts')).toContain("import { createRenderer } from '@taujs/vue';");
          }
        },
      },
      {
        name: '3 install PACKED tarballs (exactly what a user receives)',
        run: () => {
          const packed = packAll();

          // Installing the TARBALL, not the source directory: this exercises the export map, the
          // `files` allow-list and the packed declarations as published.
          const pkgPath = path.join(projectDir, 'package.json');
          const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
            dependencies: Record<string, string>;
            devDependencies: Record<string, string>;
          };
          for (const [name, tarball] of Object.entries(packed)) {
            if (pkg.dependencies?.[name]) pkg.dependencies[name] = `file:${tarball}`;
            if (pkg.devDependencies?.[name]) pkg.devDependencies[name] = `file:${tarball}`;
          }
          writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));

          execFileSync('npm', ['install', '--no-audit', '--no-fund'], { cwd: projectDir, stdio: 'pipe' });

          // Resolution goes through the export map. `import.meta.resolve`, not `require.resolve`:
          // these packages are ESM-only, so a CJS resolve cannot see their subpaths at all.
          const resolved = execFileSync(process.execPath, ['--input-type=module', '-e', `console.log(import.meta.resolve('@taujs/${framework}/renderer'))`], {
            cwd: projectDir,
            encoding: 'utf8',
          });
          expect(resolved).toContain(`${framework}/dist/renderer.js`);
        },
      },
      {
        name: '4 typecheck',
        run: () => {
          execFileSync('npm', ['run', 'lint'], { cwd: projectDir, stdio: 'pipe' });
        },
      },
      {
        name: '5 dev server boots and responds',
        run: async () => {
          [appPort, hmrPort] = await allocatePortPair();
          expect(await canBind('127.0.0.1', appPort), `allocated port ${appPort} is already in use`).toBe(true);
          expect(await canBind('127.0.0.1', hmrPort), `allocated HMR port ${hmrPort} is already in use`).toBe(true);

          const { child, output } = startServer(projectDir, 'dev', { appPort, hmrPort });
          try {
            const response = await waitForResponse(`http://127.0.0.1:${appPort}/`, child, output);

            expect(response.status, `dev responded ${response.status}\n${output()}`).toBe(200);
            const html = await response.text();
            expect(html).toContain('window.__INITIAL_DATA__');
            if (framework === 'solid') expect(html).toContain('τjs + Solid');

            // Proves HMR_PORT was honoured: the allocated HMR port is now bound. A silently
            // ignored env var would leave it free and the hardcode would survive undetected.
            expect(await canBind('127.0.0.1', hmrPort), `HMR_PORT ${hmrPort} was not bound - env var ignored`).toBe(false);
          } finally {
            await stopServer(child, [appPort, hmrPort]);
          }
        },
      },
      {
        name: '6 npm run build (the user-facing composite)',
        run: () => {
          // The COMPOSITE script, not its three parts run separately - that is the command being
          // claimed to work, and it is a distinct script that can drift from its components.
          execFileSync('npm', ['run', 'build'], { cwd: projectDir, stdio: 'pipe' });

          expect(existsSync(path.join(projectDir, 'dist/client'))).toBe(true);
          expect(existsSync(path.join(projectDir, 'dist/server/index.js'))).toBe(true);
        },
      },
      {
        name: '6a run the generated .mcp.json command against the PACKED @taujs/mcp',
        run: async () => {
          const stageName = '6a run the generated .mcp.json command against the PACKED @taujs/mcp';

          // The build (stage 6) already emitted dist/.taujs/graph.json, so taujs_overview answers
          // cold - no dev/production server needs to be running for this stage.
          const mcpJson = JSON.parse(readFileSync(path.join(projectDir, '.mcp.json'), 'utf8')) as {
            mcpServers: { taujs: { command: string; args: string[] } };
          };
          const { command, args } = mcpJson.mcpServers.taujs;

          const probe = async () => {
            const transport = new StdioClientTransport({ command, args, cwd: projectDir, stderr: 'pipe' });
            const client = new Client({ name: 'lifecycle', version: '0.0.0' });
            try {
              await client.connect(transport);

              const tools = await client.listTools();
              expect(tools.tools.map((t) => t.name).sort()).toEqual([
                'taujs_compare_graphs',
                'taujs_doctor',
                'taujs_explain_route',
                'taujs_find_contract',
                'taujs_get_episode',
                'taujs_get_episode_logs',
                'taujs_get_recent_episodes',
                'taujs_get_route',
                'taujs_list_routes',
                'taujs_overview',
                'taujs_who_calls_service',
              ]);

              const result = await client.callTool({ name: 'taujs_overview', arguments: {} });
              const structured = result.structuredContent as { ok: boolean; mode: string };
              expect(structured.ok).toBe(true);
              expect(structured.mode).toBe('stale');
            } finally {
              await client.close();
            }
          };

          await Promise.race([probe(), new Promise((_, reject) => setTimeout(() => reject(new Error(`stage "${stageName}" timed out after 30s`)), 30_000))]);
        },
      },
      {
        name: '7 production server boots and responds',
        run: async () => {
          expect(await canBind('127.0.0.1', appPort), `port ${appPort} still bound before the production boot`).toBe(true);

          const { child, output } = startServer(projectDir, 'start', { appPort, hmrPort });
          try {
            const response = await waitForResponse(`http://127.0.0.1:${appPort}/`, child, output);

            expect(response.status, `production responded ${response.status}\n${output()}`).toBe(200);
            expect(await response.text()).toContain('window.__INITIAL_DATA__');
          } finally {
            await stopServer(child, [appPort]);
          }
        },
      },
      {
        name: '8 every process dead and port released',
        run: async () => {
          for (const child of spawned) {
            expect(child.exitCode !== null || child.signalCode !== null, 'a spawned server is still running').toBe(true);
          }
          expect(await canBind('127.0.0.1', appPort), `port ${appPort} is still bound`).toBe(true);
          expect(await canBind('127.0.0.1', hmrPort), `HMR port ${hmrPort} is still bound`).toBe(true);
        },
      },
    ]);

    expect(completed).toHaveLength(9);
  });
});
